@startuml

title __MANAGE's Class Diagram__\n

  namespace  {
    namespace om.zaozhuang.newborn {
      namespace manage {
        class com.zaozhuang.newborn.manage.BabyManager {
            {static} - TAG : String
            {static} - sBabyInfo : Baby
            {static} + deleteUserInfo()
            {static} + getAge()
            {static} + getBabyInfo()
            {static} + getBirthday()
            {static} + getHeight()
            {static} + getHuangdan()
            {static} + getId()
            {static} + getImgPath()
            {static} + getName()
            {static} + getWeeks()
            {static} + getWeight()
            {static} + init()
            {static} + isBoy()
            {static} + resetInit()
            {static} + saveBabyInfo()
            {static} + setHeight()
            {static} + setHuangdan()
            {static} + setWeight()
        }
      }
    }
  }
  

  namespace  {
    namespace om.zaozhuang.newborn {
      namespace manage {
        class com.zaozhuang.newborn.manage.ConfigManager {
            {static} - TAG : String
            {static} - mConfigData : ConfigData
            {static} + delete()
            {static} + getAddress()
            {static} + getAgree()
            {static} + getCityCode()
            {static} + getFirstHot()
            {static} + getFirstRoom()
            {static} + getIsFirst()
            {static} + getIsOpenMessageTips()
            {static} + getMap()
            {static} + getReviewFlag()
            {static} + getUpgradeVersion()
            {static} + getYoungPsd()
            {static} + init()
            {static} + isFirstJoinMain()
            {static} + isFirstJoinStartSel()
            {static} + isFirstLoadGuide()
            {static} + isOpenYang()
            {static} + isRecommendSameDay()
            {static} + saveAddress()
            {static} + saveAgree()
            {static} + saveCityCode()
            {static} + saveIsFirst()
            {static} + saveIsFirstJoinMain()
            {static} + saveIsFirstLoadGuide()
            {static} + saveIsJoinStartSel()
            {static} + saveMessageTips()
            {static} + saveYoungMode()
            {static} + saveYoungPsd()
            {static} + setFirstHot()
            {static} + setFirstRoom()
            {static} + setRechargeFirstTime()
            {static} + setRecommendTime()
        }
      }
    }
  }
  

  namespace  {
    namespace om.zaozhuang.newborn {
      namespace manage {
        class com.zaozhuang.newborn.manage.UserManager {
            {static} - TAG : String
            {static} - sUserInfo : User
            {static} + deleteUserInfo()
            {static} + getName()
            {static} + getPhone()
            {static} + getPwd()
            {static} + init()
            {static} + isLogin()
            {static} + saveUserInfo()
        }
      }
    }
  }
  

  com.zaozhuang.newborn.manage.BabyManager .up.|> com.zaozhuang.newborn.config.StorageSchema
  com.zaozhuang.newborn.manage.ConfigManager .up.|> com.zaozhuang.newborn.config.StorageSchema
  com.zaozhuang.newborn.manage.UserManager .up.|> com.zaozhuang.newborn.config.StorageSchema


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
