@startuml

title __CHART's Class Diagram__\n

  namespace  {
    namespace om.zaozhuang.newborn {
      namespace chart {
        class com.zaozhuang.newborn.chart.ChartConst {
            {static} + boyHeightTitle : String
            {static} + boyWeightTitle : String
            {static} + girlHeightTitle : String
            {static} + girlWeightTitle : String
            {static} + highBoyHeight : String[]
            {static} + highBoyWeight : String[]
            {static} + highGirlHeight : String[]
            {static} + highGirlHeightTest : String[]
            {static} + highGirlWeight : String[]
            {static} + highHuangdans : String[]
            {static} + huangDanHours : String[]
            {static} + huangdanTitle : String
            {static} + lowBoyHeight : String[]
            {static} + lowBoyWeight : String[]
            {static} + lowGirlHeight : String[]
            {static} + lowGirlWeight : String[]
            {static} + lowhuangdans : String[]
            {static} + middlehuangdans : String[]
            {static} + twelveMonths : String[]
            {static} + twelveNums : String[]
            {static} + twentyFourMonths : String[]
            {static} + twentyFourNums : String[]
            {static} + xinlvKey : String[]
            {static} + xinlvValue : String[]
            {static} + xueyaValue : String[]
            {static} + xueyangValue : String[]
        }
      }
    }
  }
  

  namespace  {
    namespace om.zaozhuang.newborn {
      namespace chart {
        class com.zaozhuang.newborn.chart.ChartEntity {
            + color : int
            + curveLable : String
            + xDataList : List<String>
            + yDataList : List<String>
        }
      }
    }
  }
  

  namespace  {
    namespace om.zaozhuang.newborn {
      namespace chart {
        class com.zaozhuang.newborn.chart.ChartUtil {
            {static} + showChart2()
            {static} - getLegendEntries()
            {static} - setLineData()
            {static} - setLineDataSet()
        }
      }
    }
  }
  

  namespace  {
    namespace om.zaozhuang.newborn {
      namespace chart {
        class com.zaozhuang.newborn.chart.CustomMarkerView {
            - tvContent : TextView
            - unitName : String
            + CustomMarkerView()
            + getOffset()
            + refreshContent()
        }
      }
    }
  }
  

  namespace  {
    namespace om.zaozhuang.newborn {
      namespace chart {
        class com.zaozhuang.newborn.chart.LegendEntity {
            + color : int
            + label : String
        }
      }
    }
  }
  

  namespace  {
    namespace om.zaozhuang.newborn {
      namespace chart {
        class com.zaozhuang.newborn.chart.MyFillFormatter {
            + getFillLinePosition()
        }
      }
    }
  }
  

  com.zaozhuang.newborn.chart.CustomMarkerView -up-|> com.github.mikephil.charting.components.MarkerView
  com.zaozhuang.newborn.chart.MyFillFormatter .up.|> com.github.mikephil.charting.formatter.IFillFormatter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
