@startuml

title __CONFIG's Class Diagram__\n

  namespace  {
    namespace om.zaozhuang.newborn {
      namespace config {
        interface com.zaozhuang.newborn.config.Const {
            {static} + ANDROID_DATA : String
            {static} + CONFIG_PATH : String
            {static} + CRASH : String
            {static} + CROP_IMAGE : String
            {static} + CUSTOMER_SERVICE_ID : String
            {static} + DATA : String
            {static} + DOWNLOAD : String
            {static} + GIFT_SVGA_PATH : String
            {static} + GSON : Gson
            {static} + HX_PROD_KEY : String
            {static} + HX_TEST_KEY : String
            {static} + IMG : String
            {static} + JUMPER : Jumper
            {static} + LOG : String
            {static} + QQ : String
            {static} + RECORD_PATH : String
            {static} + RTM_IMAGE_PATH : String
            {static} + SCHEME_DYNAMIC : String
            {static} + SCHEME_ROOM : String
            {static} + SCHEME_USER : String
            {static} + SIMPLE_URL : String
            {static} + SYSTEM_ID : String
            {static} + UM_KEY : String
            {static} + UPLOAD_IMAGE : String
            {static} + VOICE_PATH : String
            {static} + WEBVIEW : String
            {static} + WX : String
        }
      }
    }
  }
  

  namespace  {
    namespace om.zaozhuang.newborn {
      namespace config {
        interface com.zaozhuang.newborn.config.Jumper {
            {abstract} + babyAdd()
            {abstract} + babyAdd()
            {abstract} + babyKnowledge()
            {abstract} + blueConnect2()
            {abstract} + chart()
            {abstract} + chart()
            {abstract} + contact()
            {abstract} + familyDoctor()
            {abstract} + heightInput()
            {abstract} + huangdanInput()
            {abstract} + knowledge()
            {abstract} + login()
            {abstract} + phone()
            {abstract} + register()
            {abstract} + sliding()
            {abstract} + touchEventTest()
            {abstract} + transmit()
            {abstract} + userInfo()
            {abstract} + videoList()
            {abstract} + videoPlayer()
            {abstract} + volleyTest()
            {abstract} + weightInput()
            {abstract} + xinlv()
            {abstract} + xueya()
            {abstract} + xueyang()
        }
      }
    }
  }
  

  namespace  {
    namespace om.zaozhuang.newborn {
      namespace config {
        interface com.zaozhuang.newborn.config.StorageSchema {
            {static} + BABY_INFO : Storage<Baby>
            {static} + CAHAT_ID : Storage<String>
            {static} + CAN_SEND : Storage<Boolean>
            {static} + CHANNEL_NAME : Storage<String>
            {static} + CONFIG : Storage<ConfigData>
            {static} + FLEET_INFO : Storage<String>
            {static} + SEARCH_HISTORY : Storage<String>
            {static} + USER_INFO : Storage<User>
            {static} + WIFI_MAC : Storage<String>
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
